version: "3.8"

services:
  # Development service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4321:4321"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.astro
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - makerfriends

  # Production build service (optional)
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    networks:
      - makerfriends
    profiles:
      - production

  # Development with additional tools
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4321:4321"
      - "24678:24678" # Vite HMR port
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.astro
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0 --port 4321
    stdin_open: true
    tty: true
    networks:
      - makerfriends
    profiles:
      - dev-tools

networks:
  makerfriends:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  node_modules:
  astro_cache:
