#!/usr/bin/env sh
set -e

# Load nodenv and use the version specified in .node-version
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"

# Add node_modules/.bin to PATH
export PATH="$PATH:$(pwd)/node_modules/.bin"

# Run code quality checks
npm run lint:strict
npm run format:check